package com.jetsynthesys.rightlife.ai_package.model.response

data class MyRecipeResponse(
    val status_code: Int,
    val message: String,
    val data: List<MyRecipe>
)

data class MyRecipe(
    val _id: String,
    val user_id: String,
    val recipe_id: String,
    val recipe: String,
    val meal_type: String,
    val cuisine: String,
    val regional_split: String,
    val category: String,
    val flag: String,
    val serving_size_for_calorific_breakdown: String,
    val calories_kcal: Double,
    val carbs_g: Double,
    val protein_g: Double,
    val fat_g: Double,
    val sodium_mg: Double,
    val potassium_mg: Double,
    val vit_a_mcg: Double,
    val vit_c_mg: Double,
    val vit_d_mcg: Double,
    val vit_k_mcg: Double,
    val vit_b6_mg: Double,
    val folate_b9_mcg: Double,
    val vit_b12_mcg: Double,
    val calcium_mg: Double,
    val iron_mg: Double,
    val magnesium_mg: Double,
    val zinc_mg: Double,
    val phosphorus_mg: Double,
    val fiber_g: Double,
    val sugars_g: Double,
    val vit_e_mg: Double,
    val thiamin_b1_mg: Double,
    val riboflavin_b2_mg: Double,
    val niacin_b3_mg: Double,
    val omega3_g: Double,
    val ingredients: List<Ingredient>,
    var isRecipeLog : Boolean = false
)

data class Ingredient(
    val ingredient_id: String,
    val ingredient_name: String,
    val quantity: Double,
    val standard_serving_size: String,
    val description: String,
    val food_category: String,
    val photo_url: String,
    val calories_kcal: Double,
    val carbs_g: Double,
    val sugars_g: Double,
    val fiber_g: Double,
    val protein_g: Double,
    val fat_g: Double,
    val vit_a_mcg: Double,
    val sodium_mg: Double,
    val potassium_mg: Double,
    val vit_c_mg: Double,
    val vit_d_mcg: Double,
    val vit_k_mcg: Double,
    val vit_b6_mg: Double,
    val folate_b9_mcg: Double,
    val vit_b12_mcg: Double,
    val calcium_mg: Double,
    val iron_mg: Double,
    val magnesium_mg: Double,
    val zinc_mg: Double,
    val vit_e_mg: Double,
    val thiamin_b1_mg: Double,
    val riboflavin_b2_mg: Double,
    val niacin_b3_mg: Double,
    val phosphorus_mg: Double,
    val omega3_g: Double
)


